server:
  port: 8088

spring:
    datasource:
        name: authority-datasource
        url: jdbc:mysql://localhost:3306/lxyw-authority?useUnicode=true&characterEncoding=utf8
        username: root
        password: root6299383
        driverClassName: com.mysql.cj.jdbc.Driver
#mybatis
mybatis:
  type-aliases-package: com.lxyw.authority.entity
  #mapper-locations: "classpath:*Mapper.xml"
  #mappers 多个接口时逗号隔开
  mappers: tk.mybatis.mapper.common.Mapper,tk.mybatis.mapper.common.MySqlMapper
  not-empty:  false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql