server:
  port: 8088

spring:
    datasource:
        name: authority-datasource
        url: jdbc:mysql://localhost:3306/lxyw-authority?useUnicode=true&characterEncoding=utf8
        username: root
        password: root6299383
        driverClassName: com.mysql.cj.jdbc.Driver

mapper:
  mappers:  com.lxyw.authority.mapper.CommonMapper
  not-empty:  false
  identity: MYSQL